# Generated by Django 5.0 on 2023-12-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='task-images/')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('Select', 'Select'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Select', max_length=1000)),
                ('status', models.CharField(choices=[('Select', 'Select'), ('incomolete', 'incomolete'), ('comolete', 'comolete')], default='Select', max_length=1000)),
                ('image', models.ManyToManyField(blank=True, to='tasks.taskimage')),
            ],
        ),
    ]
